# Generated by Django 4.2.4 on 2023-09-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa1', '0002_alter_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='isComplated',
            field=models.BooleanField(default=False),
        ),
    ]
